name=HP303B Barometric Pressure Sensor
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for HP303B Barometric Pressure and Temperature Sensor
paragraph=This library provides an easy-to-use API for the HP303B barometric sensor, capable of measuring atmospheric pressure and temperature with high precision. It supports both I2C and SPI communication protocols, making it ideal for altimeters, weather stations, and indoor navigation in Arduino or PlatformIO projects.
category=Sensors
url=https://github.com/Boardoza/Boardoza_HP303B
architectures=*